const KEY='weicon-crm-v2';
const seed={customers:[{id:'M-0001',name:'Örnek Makina Sanayi',city:'Ankara',contact:'Ahmet Yılmaz',phone:'0532 000 00 00',last:'Ziyaret',lastDate:'2026-08-14',status:'Aktif',products:['VA 1408','W 44 T']}],products:[{id:'P-001',name:'VA 1408',berta:'',abas:'',price:0,category:'Siyanoakrilat'},{id:'P-002',name:'W 44 T',berta:'',abas:'',price:0,category:'Teknik Sprey'}],tasks:[],visits:[],sales:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; let route='dashboard';
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function money(n){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'EUR'}).format(Number(n)||0)}
function nav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route))}
function render(){nav(); ({dashboard:renderDashboard,customers:renderCustomers,sales:renderSales,products:renderProducts,tasks:renderTasks,reports:renderReports}[route]||renderDashboard)();}
function header(kicker,title,sub=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1 class="page-title">${title}</h1>${sub?`<div class="muted">${sub}</div>`:''}</div></div>`}
function renderDashboard(){let overdue=db.tasks.filter(x=>!x.done&&x.date<=new Date().toISOString().slice(0,10)).length;let active=db.customers.filter(x=>x.status!=='Pasif').length;let open=db.sales.filter(x=>x.stage!=='Sipariş').length;$('#app').innerHTML=header('SATIŞ YÖNETİMİ','Günaydın Abdullah','Bugünün saha satış özeti ve öncelikleri')+`<div class="grid grid-4"><div class="card metric blue"><span>AKTİF MÜŞTERİ</span><strong>${active}</strong></div><div class="card metric orange"><span>AÇIK SATIŞ SÜRECİ</span><strong>${open}</strong></div><div class="card metric red"><span>GECİKEN GÖREV</span><strong>${overdue}</strong></div><div class="card metric green"><span>BU AY SİPARİŞ</span><strong>${db.sales.filter(x=>x.stage==='Sipariş').length}</strong></div></div><div class="grid grid-2" style="margin-top:16px"><section class="card"><h2 class="section-title">Hızlı İşlemler</h2><div class="action-grid"><button class="action" onclick="openCustomerForm()"><strong>＋ Yeni Müşteri</strong><span>Müşteri kartı oluştur</span></button><button class="action" onclick="route='sales';render()"><strong>＋ Yeni Satış</strong><span>Tekliften siparişe ilerle</span></button><button class="action" onclick="route='tasks';render()"><strong>✓ Görevlerim</strong><span>Takipleri yönet</span></button><button class="action" onclick="route='reports';render()"><strong>▥ Raporlar</strong><span>Performansı gör</span></button></div></section><section class="card"><h2 class="section-title">Öncelikler</h2>${priorityHtml()}</section></div>`}
function priorityHtml(){let t=db.tasks.filter(x=>!x.done).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5); if(!t.length)return '<div class="empty">Bekleyen görev yok.</div>';return t.map(x=>`<div class="task-row"><div class="avatar">✓</div><div class="grow"><div class="name">${esc(x.title)}</div><div class="small">${esc(x.customer)} · ${esc(x.date)}</div></div><span class="badge ${x.date<=new Date().toISOString().slice(0,10)?'red':'orange'}">${x.date}</span></div>`).join('')}
function renderCustomers(){let q=(window.cq||'').toLocaleLowerCase('tr-TR');let list=db.customers.filter(x=>(x.name+' '+x.city+' '+x.contact).toLocaleLowerCase('tr-TR').includes(q));$('#app').innerHTML=header('CRM','Müşteriler',`${db.customers.length} kayıt · müşteri hafızası`)+`<div class="toolbar"><input class="input search" placeholder="Müşteri, şehir veya yetkili ara…" value="${esc(window.cq||'')}" oninput="window.cq=this.value;renderCustomers()"><button class="btn primary" onclick="openCustomerForm()">＋ Yeni Müşteri</button></div><section class="card">${list.length?list.map(customerRow).join(''):'<div class="empty">Müşteri bulunamadı.</div>'}</section>`}
function customerRow(c){return `<div class="customer-row" onclick="openCustomer('${c.id}')"><div class="avatar">${esc((c.name||'?')[0])}</div><div class="grow"><div class="name">${esc(c.name)}</div><div class="small">${esc(c.city)} · ${esc(c.contact||'Yetkili yok')}</div></div><div style="text-align:right"><span class="badge ${c.status==='Pasif'?'red':'green'}">${esc(c.status||'Aktif')}</span><div class="small" style="margin-top:5px">${esc(c.last||'Hareket yok')}</div></div></div>`}
function openCustomer(id){let c=db.customers.find(x=>x.id===id);if(!c)return;let sales=db.sales.filter(x=>x.customerId===id),tasks=db.tasks.filter(x=>x.customerId===id),visits=db.visits.filter(x=>x.customerId===id);modal(`<div class="modal-head"><div><div class="eyebrow">MÜŞTERİ KARTI</div><h2 class="page-title">${esc(c.name)}</h2><div class="muted">${esc(c.city)} · ${esc(c.contact||'Yetkili yok')} · ${esc(c.phone||'Telefon yok')}</div></div><button class="close" onclick="closeModal()">×</button></div><div class="grid grid-4"><div class="card metric blue"><span>SON HAREKET</span><strong style="font-size:18px">${esc(c.last||'—')}</strong></div><div class="card metric orange"><span>SATIŞ</span><strong>${sales.length}</strong></div><div class="card metric green"><span>GÖREV</span><strong>${tasks.filter(x=>!x.done).length}</strong></div><div class="card metric red"><span>ZİYARET</span><strong>${visits.length}</strong></div></div><div class="card" style="margin-top:16px"><h3 class="section-title">İşlemler</h3><div class="action-grid"><button class="action" onclick="quickTask('${c.id}')"><strong>✓ Görev Gir</strong><span>Takip tarihi oluştur</span></button><button class="action" onclick="quickVisit('${c.id}')"><strong>⌖ Ziyaret Kaydet</strong><span>Son hareketi güncelle</span></button><button class="action" onclick="quickSale('${c.id}')"><strong>＋ Satış Süreci</strong><span>Teklif / numune / proforma / sipariş</span></button><button class="action" onclick="showCustomerHistory('${c.id}')"><strong>◷ İşlem Geçmişi</strong><span>Tüm temasları gör</span></button></div></div>`)}
function renderProducts(){let q=(window.pq||'').toLocaleLowerCase('tr-TR');let list=db.products.filter(x=>(x.name+' '+x.berta+' '+x.abas+' '+x.category).toLocaleLowerCase('tr-TR').includes(q));$('#app').innerHTML=header('KATALOG','Ürünler','BERTA / ABAS, fiyat ve hızlı satış')+`<div class="toolbar"><input class="input search" placeholder="Ürün adı, BERTA, ABAS ara…" value="${esc(window.pq||'')}" oninput="window.pq=this.value;renderProducts()"><button class="btn primary" onclick="openProductForm()">＋ Ürün Ekle</button></div><section class="card">${list.length?list.map(p=>`<div class="product-row"><div class="avatar">▦</div><div class="grow"><div class="name">${esc(p.name)}</div><div class="small">${esc(p.category||'')} · BERTA ${esc(p.berta||'—')} · ABAS ${esc(p.abas||'—')}</div></div><strong>${money(p.price)}</strong><button class="btn light" onclick="startSaleProduct('${p.id}')">Sepete</button></div>`).join(''):'<div class="empty">Ürün bulunamadı.</div>'}</section>`}
function renderSales(){let stages=['Teklif','Numune','Proforma','Sipariş'];$('#app').innerHTML=header('SATIŞ','Satış Süreçleri','İhtiyaçtan siparişe tek akış')+`<div class="toolbar"><button class="btn primary" onclick="quickSale()">＋ Yeni Satış</button></div><div class="grid grid-2">${stages.map(s=>`<section class="card"><h2 class="section-title">${s} <span class="small">${db.sales.filter(x=>x.stage===s).length}</span></h2>${db.sales.filter(x=>x.stage===s).map(x=>`<div class="task-row"><div class="grow"><div class="name">${esc(x.customer)}</div><div class="small">${esc(x.product||'Ürün belirtilmedi')} · ${money(x.total)}</div></div><button class="btn light" onclick="advanceSale('${x.id}')">İlerle →</button></div>`).join('')||'<div class="empty">Kayıt yok</div>'}</section>`).join('')}</div>`}
function renderTasks(){let show=db.tasks.filter(x=>!x.done);$('#app').innerHTML=header('TAKİP','Görevlerim',`${show.length} açık görev`)+`<div class="toolbar"><button class="btn primary" onclick="quickTask()">＋ Görev Gir</button></div><section class="card">${show.map(x=>`<div class="task-row"><div class="avatar">✓</div><div class="grow"><div class="name">${esc(x.title)}</div><div class="small">${esc(x.customer)} · ${esc(x.date)}</div></div><button class="btn green" onclick="completeTask('${x.id}')">Tamamla</button></div>`).join('')||'<div class="empty">Açık görev yok.</div>'}</section>`}
function renderReports(){$('#app').innerHTML=header('YÖNETİM','Raporlar','Saha performansı ve satış hunisi')+`<div class="grid grid-4"><div class="card metric blue"><span>MÜŞTERİ</span><strong>${db.customers.length}</strong></div><div class="card metric orange"><span>TEKLİF</span><strong>${db.sales.filter(x=>x.stage==='Teklif').length}</strong></div><div class="card metric green"><span>SİPARİŞ</span><strong>${db.sales.filter(x=>x.stage==='Sipariş').length}</strong></div><div class="card metric red"><span>GÖREV</span><strong>${db.tasks.filter(x=>!x.done).length}</strong></div></div><section class="card" style="margin-top:16px"><h2 class="section-title">Satış Hunisi</h2>${['Teklif','Numune','Proforma','Sipariş'].map(s=>`<div class="task-row"><div class="grow"><b>${s}</b></div><strong>${db.sales.filter(x=>x.stage===s).length}</strong></div>`).join('')}</section>`}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal-back" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}function closeModal(){$('#modalRoot').innerHTML=''}
function openCustomerForm(){modal(`<div class="modal-head"><h2>Yeni Müşteri</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><label>Firma adı<input id="fName" class="input"></label><label>Şehir<input id="fCity" class="input"></label><label>Yetkili<input id="fContact" class="input"></label><label>Telefon<input id="fPhone" class="input"></label></div><button class="btn primary" style="margin-top:16px" onclick="saveCustomer()">Müşteriyi Kaydet</button>`)}
function saveCustomer(){let name=$('#fName').value.trim();if(!name)return alert('Firma adı zorunlu.');db.customers.push({id:'M-'+String(Date.now()).slice(-6),name,city:$('#fCity').value,contact:$('#fContact').value,phone:$('#fPhone').value,status:'Aktif',last:'Yeni müşteri'});save();closeModal();route='customers';render()}
function quickTask(customerId){let c=customerId&&db.customers.find(x=>x.id===customerId);modal(`<div class="modal-head"><h2>Görev Gir</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><label class="full">Müşteri<input id="tCustomer" class="input" value="${esc(c?.name||'')}"></label><label class="full">Görev<input id="tTitle" class="input" placeholder="Örn. Numune sonucu ara"></label><label>Tarih<input id="tDate" type="date" class="input" value="${new Date().toISOString().slice(0,10)}"></label></div><button class="btn primary" style="margin-top:16px" onclick="saveTask('${customerId||''}')">Görevi Kaydet</button>`)}
function saveTask(cid){let title=$('#tTitle').value.trim();if(!title)return;let c=cid&&db.customers.find(x=>x.id===cid);db.tasks.push({id:'T-'+Date.now(),customerId:cid||'',customer:c?.name||$('#tCustomer').value,title,date:$('#tDate').value,done:false});save();closeModal();render();}
function completeTask(id){let t=db.tasks.find(x=>x.id===id);if(t)t.done=true;save();render()}
function quickVisit(cid){let c=db.customers.find(x=>x.id===cid);if(!c)return; c.last='Ziyaret';c.lastDate=new Date().toISOString().slice(0,10);db.visits.push({id:'V-'+Date.now(),customerId:cid,customer:c.name,date:c.lastDate});save();closeModal();render();}
function quickSale(cid){let c=cid&&db.customers.find(x=>x.id===cid);modal(`<div class="modal-head"><h2>Yeni Satış Süreci</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><label>Müşteri<input id="sCustomer" class="input" value="${esc(c?.name||'')}"></label><label>Ürün<input id="sProduct" class="input" placeholder="Ürün adı"></label><label>Süreç<select id="sStage" class="select">${['Teklif','Numune','Proforma','Sipariş'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Tutar (€)<input id="sTotal" type="number" class="input" value="0"></label></div><button class="btn primary" style="margin-top:16px" onclick="saveSale('${cid||''}')">Süreci Kaydet</button>`)}
function saveSale(cid){let c=cid&&db.customers.find(x=>x.id===cid);db.sales.push({id:'S-'+Date.now(),customerId:cid||'',customer:c?.name||$('#sCustomer').value,product:$('#sProduct').value,stage:$('#sStage').value,total:Number($('#sTotal').value)||0});if(c){c.last=$('#sStage').value;c.lastDate=new Date().toISOString().slice(0,10)}save();closeModal();route='sales';render()}
function advanceSale(id){let x=db.sales.find(s=>s.id===id);if(!x)return;let stages=['Teklif','Numune','Proforma','Sipariş'];let i=stages.indexOf(x.stage);if(i<3)x.stage=stages[i+1];save();render()}
function openProductForm(){modal(`<div class="modal-head"><h2>Ürün Ekle</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><label>Ürün adı<input id="pName" class="input"></label><label>Kategori<input id="pCat" class="input"></label><label>BERTA<input id="pBerta" class="input"></label><label>ABAS<input id="pAbas" class="input"></label><label>Liste fiyatı (€)<input id="pPrice" type="number" class="input"></label></div><button class="btn primary" style="margin-top:16px" onclick="saveProduct()">Ürünü Kaydet</button>`)}
function saveProduct(){let n=$('#pName').value.trim();if(!n)return;db.products.push({id:'P-'+Date.now(),name:n,category:$('#pCat').value,berta:$('#pBerta').value,abas:$('#pAbas').value,price:Number($('#pPrice').value)||0});save();closeModal();render()}
function startSaleProduct(id){let p=db.products.find(x=>x.id===id);quickSale();setTimeout(()=>{if(p&&$('#sProduct'))$('#sProduct').value=p.name},0)}
function showCustomerHistory(id){let c=db.customers.find(x=>x.id===id),items=[...db.visits.filter(x=>x.customerId===id).map(x=>({date:x.date,type:'Ziyaret'})),...db.sales.filter(x=>x.customerId===id).map(x=>({date:x.date||'—',type:x.stage,product:x.product}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));modal(`<div class="modal-head"><h2>${esc(c.name)} · İşlem Geçmişi</h2><button class="close" onclick="closeModal()">×</button></div><div class="timeline">${items.map(x=>`<div class="timeline-item"><b>${esc(x.type)}</b><div class="small">${esc(x.date)}${x.product?' · '+esc(x.product):''}</div></div>`).join('')||'<div class="empty">Henüz hareket yok.</div>'}</div>`)}
$('#globalSearchBtn').onclick=()=>{route='customers';render();setTimeout(()=>document.querySelector('.search')?.focus(),50)};$('#notifyBtn').onclick=()=>{route='tasks';render()};$('#menuBtn').onclick=()=>modal(`<div class="modal-head"><h2>Menü</h2><button class="close" onclick="closeModal()">×</button></div><div class="menu-list"><button onclick="route='dashboard';closeModal();render()">⌂ Ana Sayfa</button><button onclick="route='reports';closeModal();render()">▥ Raporlar</button><button onclick="alert('V2 veri alanı: '+JSON.stringify(db).length+' karakter')">▣ Veri Durumu</button></div>`);
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});
function updateBadge(){let n=db.tasks.filter(x=>!x.done&&x.date<=new Date().toISOString().slice(0,10)).length;$('#notifyBadge').textContent=n;}
updateBadge();render();