/* WE-CON-CRM Sales V2
 * New Sales area: Müşteri / İşlemler.
 * UI-only integration layer. Legacy data and functions remain intact.
 */
(function(global){
  'use strict';
  var state={tab:'customer',historyType:'all',contactType:'all',historyPage:0};
  var PAGE=15;
  function esc(v){if(typeof safeText==='function')return safeText(v==null?'':String(v));return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function currentCustomer(){return global.seciliMusteri||null;}
  function closeSales(){var el=document.getElementById('satisMenusuModal');if(el)el.style.display='none';}
  function requireCustomer(){var m=currentCustomer();if(m)return m;if(typeof showToast==='function')showToast('Önce müşteri seçin.',3000);closeSales();if(typeof musteriSecimBaslat==='function')musteriSecimBaslat(1);else if(typeof switchTab==='function')switchTab(7);return null;}
  function customerLabel(){var m=currentCustomer();return m?esc(m.ad||'-'):'Henüz müşteri seçilmedi';}
  function selectedAuthorities(){var list=global.seciliYetkiliKisiler;if(Array.isArray(list)&&list.length)return list;if(global.seciliYetkiliKisi)return[global.seciliYetkiliKisi];var saved=null;try{saved=JSON.parse(localStorage.getItem('weicon_secili_yetkililer')||'null');}catch(e){}if(Array.isArray(saved))return saved;try{var one=JSON.parse(localStorage.getItem('weicon_secili_yetkili')||'null');if(one)return[one];}catch(e){}return[];}
  function render(){var modal=document.getElementById('satisMenusuModal');if(!modal)return;modal.innerHTML='<div id="salesV2Sheet" style="background:#f7f9fc;border-radius:22px;width:96%;max-width:760px;max-height:94vh;overflow:hidden;box-sizing:border-box;box-shadow:0 18px 60px rgba(0,0,0,.28);"><div style="background:linear-gradient(135deg,#0b3b78,#1456a3);color:#fff;padding:22px 20px 16px;"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px;"><div><div style="font-size:14px;font-weight:800;opacity:.78;letter-spacing:.8px;">WEİCON ASİST · SATIŞ</div><div style="font-size:30px;font-weight:900;margin-top:2px;">Satış Merkezi</div></div><button onclick="window.WEICONSalesV2.close()" style="border:0;background:rgba(255,255,255,.14);color:#fff;border-radius:12px;padding:10px 14px;font-size:22px;">✕</button></div><div style="margin-top:16px;background:rgba(255,255,255,.11);border:1px solid rgba(255,255,255,.2);border-radius:13px;padding:10px 12px;display:flex;align-items:center;gap:10px;"><span style="font-size:20px;">👤</span><div style="min-width:0;flex:1;"><div style="font-size:11px;opacity:.72;font-weight:800;">SEÇİLİ MÜŞTERİ</div><div style="font-size:18px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">'+customerLabel()+'</div></div></div></div><div style="padding:14px 14px 0;background:#fff;"><div style="display:grid;grid-template-columns:1fr 1fr;background:#eef2f7;border-radius:14px;padding:4px;gap:4px;">'+tabButton('customer','👥','Müşteri')+tabButton('operations','▦','İşlemler')+'</div></div><div id="salesV2Content" style="padding:14px;max-height:calc(94vh - 190px);overflow:auto;background:#fff;"></div></div>';modal.style.display='flex';modal.style.alignItems='flex-start';modal.style.paddingTop='12px';modal.style.background='rgba(15,23,42,.62)';renderTab();}
  function tabButton(tab,icon,label){var active=state.tab===tab;return '<button onclick="window.WEICONSalesV2.tab(\''+tab+'\')" style="border:0;border-radius:11px;padding:13px 8px;background:'+(active?'#fff':'transparent')+';color:'+(active?'#0b3b78':'#65758b')+';font-size:17px;font-weight:900;box-shadow:'+(active?'0 2px 8px rgba(15,23,42,.08)':'none')+';">'+icon+' &nbsp;'+label+'</button>';}
  function renderTab(){var el=document.getElementById('salesV2Content');if(!el)return;el.innerHTML=state.tab==='customer'?customerView():operationsView();}
  function customerView(){var m=currentCustomer();var customerCard=m?'<div style="background:#f5f9ff;border:1px solid #c9dbf3;border-radius:16px;padding:16px;"><div style="font-size:12px;color:#6b7d93;font-weight:900;letter-spacing:.7px;">AKTİF MÜŞTERİ</div><div style="font-size:24px;font-weight:900;color:#123d70;margin-top:4px;">'+esc(m.ad||'-')+'</div><div style="font-size:14px;color:#64748b;margin-top:5px;">'+esc((m.sehir||'')+(m.id?' · '+m.id:''))+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px;">'+actionCard('Müşteri Kartı','Firma bilgileri ve hafıza','🏢','#0b3b78','window.WEICONSalesV2.customerCard()')+actionCard('Yetkililer','Kişi seçimi ve iletişim','👥','#7c3aed','window.WEICONSalesV2.authorities()')+'</div></div>':'<div style="background:#f8fafc;border:2px dashed #cbd5e1;border-radius:16px;padding:22px;text-align:center;"><div style="font-size:46px;">👤</div><div style="font-size:20px;font-weight:900;color:#243b53;margin-top:7px;">Satış için müşteri seçin</div><div style="font-size:14px;color:#718096;margin-top:5px;">Müşteri seçildiğinde kart ve yetkililer burada aktifleşir.</div><button onclick="window.WEICONSalesV2.startSale()" style="margin-top:14px;width:100%;border:0;border-radius:12px;background:#0b3b78;color:#fff;padding:14px;font-size:17px;font-weight:900;">Müşteri Seç</button></div>';var auth=selectedAuthorities();var selected=auth.length?'<div style="margin-top:10px;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:13px;padding:12px;"><div style="font-size:11px;color:#6d28d9;font-weight:900;">SEÇİLİ YETKİLİLER</div><div style="font-size:14px;color:#4c1d95;font-weight:800;margin-top:4px;">'+auth.map(function(x){return esc(x.isim||x.ad||x.name||'Yetkili');}).join(' · ')+'</div></div>':'';var sales='<div style="margin-top:12px;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:16px;"><div style="font-size:12px;font-weight:900;color:#64748b;letter-spacing:.7px;">SATIŞ AKIŞI</div><div style="display:flex;align-items:center;gap:6px;margin:12px 0 14px;overflow:auto;">'+step('1','Müşteri')+'<span>›</span>'+step('2','Yetkili')+'<span>›</span>'+step('3','Ürün Bul')+'<span>›</span>'+step('4','Hesapla')+'</div><button onclick="window.WEICONSalesV2.startSale()" style="width:100%;border:0;border-radius:13px;background:linear-gradient(135deg,#16a34a,#0f8a3e);color:#fff;padding:17px;font-size:20px;font-weight:900;">🔎 Ürün Bul ile Satış Başlat</button></div>';return customerCard+selected+sales;}
  function actionCard(title,sub,icon,color,onclick){return '<button onclick="'+onclick+'" style="text-align:left;border:1px solid #e2e8f0;border-radius:13px;background:#fff;padding:14px;min-height:105px;box-shadow:0 2px 8px rgba(15,23,42,.04);"><div style="font-size:28px;">'+icon+'</div><div style="font-size:17px;font-weight:900;color:'+color+';margin-top:5px;">'+title+'</div><div style="font-size:12px;color:#64748b;margin-top:2px;">'+sub+'</div></button>';}
  function step(n,label){return '<div style="min-width:72px;text-align:center;"><div style="margin:auto;width:29px;height:29px;border-radius:50%;background:#0b3b78;color:#fff;font-weight:900;line-height:29px;font-size:13px;">'+n+'</div><div style="font-size:11px;font-weight:800;color:#52647a;margin-top:5px;">'+label+'</div></div>';}
  function operationsView(){var m=currentCustomer();var head='<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:15px;padding:14px;"><div style="font-size:12px;font-weight:900;color:#64748b;letter-spacing:.7px;">İŞLEMLER</div><div style="font-size:21px;font-weight:900;color:#1e293b;margin-top:4px;">'+(m?esc(m.ad):'Müşteri seçilmedi')+'</div><div style="font-size:13px;color:#64748b;margin-top:3px;">Geçmiş, temas notları ve görevler tek merkezde.</div></div>';var cards='<div style="display:grid;grid-template-columns:1fr;gap:10px;margin-top:12px;">'+bigOp('Geçmiş İşlemler','Sipariş · Teklif · Proforma · Numune','🧾','#0b3b78','window.WEICONSalesV2.history()')+bigOp('Müşteri ile Temas','Ziyaret · Telefon · Mail · WhatsApp','💬','#0f766e','window.WEICONSalesV2.contacts()')+bigOp('Görevler','Kendine görev ata · Tarih · Saat · Hatırlatma','☑️','#7c3aed','window.WEICONSalesV2.tasks()')+'</div>';return head+cards;}
  function bigOp(title,sub,icon,color,onclick){return '<button onclick="'+onclick+'" style="width:100%;text-align:left;border:1px solid #dbe4ef;border-left:5px solid '+color+';border-radius:15px;background:#fff;padding:16px;display:flex;align-items:center;gap:13px;box-shadow:0 2px 8px rgba(15,23,42,.04);"><div style="width:48px;height:48px;border-radius:13px;background:'+color+'14;display:flex;align-items:center;justify-content:center;font-size:28px;">'+icon+'</div><div style="flex:1;min-width:0;"><div style="font-size:19px;font-weight:900;color:#1e293b;">'+title+'</div><div style="font-size:13px;color:#64748b;margin-top:3px;">'+sub+'</div></div><span style="font-size:26px;color:#94a3b8;">›</span></button>';}
  function openCurrentCustomerCard(){var m=requireCustomer();if(!m)return;closeSales();var idx=global.musteriKartIdx;if(idx===null||idx===undefined){global.musteriListesi=typeof lsGet==='function'?lsGet('weicon_musteriler',[]):[];idx=global.musteriListesi.findIndex(function(x){return x===m||(x.id&&m.id&&x.id===m.id);});}if(typeof musteriKartAc==='function'&&idx>=0)musteriKartAc(idx);else if(typeof switchTab==='function')switchTab(7);}
  function openAuthorities(){var m=requireCustomer();if(!m)return;closeSales();if(typeof musteriIletisimYetkiliSecmeyeAc==='function')musteriIletisimYetkiliSecmeyeAc();else if(typeof showToast==='function')showToast('Yetkili ekranı mevcut müşteri kartından açılabilir.');}
  function startSale(){var m=currentCustomer();if(!m){closeSales();if(typeof musteriSecimBaslat==='function')musteriSecimBaslat(1);else switchTab(7);return;}closeSales();if(typeof musteriIslemBaslatKarttan==='function')musteriIslemBaslatKarttan();else if(typeof switchTab==='function')switchTab(1);}
  function historyData(){var m=currentCustomer();if(!m)return[];var a=global.arsivData||{};var out=[];var types=['siparis','teklif','proforma','numune'];var labels={siparis:'Sipariş',teklif:'Teklif',proforma:'Proforma',numune:'Numune'};types.forEach(function(t){(a[t]||[]).forEach(function(r,i){var same=(m.id&&r.musteriId&&String(m.id)===String(r.musteriId))||String(r.musteri||'').trim().toLocaleLowerCase('tr-TR')===String(m.ad||'').trim().toLocaleLowerCase('tr-TR');if(same)out.push({type:t,label:labels[t],date:r.tarih||'',ts:r.ts||0,record:r,index:i});});});out.sort(function(a,b){return(b.ts||0)-(a.ts||0)||String(b.date).localeCompare(String(a.date));});return out;}
  function history(){var m=requireCustomer();if(!m)return;state.historyType='all';state.historyPage=0;showPanel('İŞLEMLER · GEÇMİŞ',historyHtml());}
  function historyHtml(){var data=historyData();var filtered=state.historyType==='all'?data:data.filter(function(x){return x.type===state.historyType;});var start=state.historyPage*PAGE,page=filtered.slice(start,start+PAGE);var filters=['all','siparis','teklif','proforma','numune'];var html='<div style="display:flex;gap:7px;overflow:auto;padding-bottom:8px;">';filters.forEach(function(f){var label={all:'Tümü',siparis:'Sipariş',teklif:'Teklif',proforma:'Proforma',numune:'Numune'}[f];html+='<button onclick="window.WEICONSalesV2.historyFilter(\''+f+'\')" style="white-space:nowrap;border:1px solid '+(state.historyType===f?'#0b3b78':'#d5deea')+';background:'+(state.historyType===f?'#eaf2ff':'#fff')+';color:'+(state.historyType===f?'#0b3b78':'#64748b')+';border-radius:20px;padding:8px 12px;font-weight:900;">'+label+'</button>';});html+='</div>';if(!page.length)html+='<div style="padding:35px 10px;text-align:center;color:#94a3b8;font-weight:800;">Bu filtrede kayıt yok.</div>';page.forEach(function(x){var total=0;(x.record.urunler||[]).forEach(function(u){total+=Number(u.toplamEuro||0);});html+='<div style="border:1px solid #e2e8f0;border-radius:14px;padding:14px;margin-top:9px;background:#fff;"><div style="display:flex;justify-content:space-between;gap:8px;"><span style="font-size:13px;font-weight:900;color:#0b3b78;">'+x.label.toUpperCase()+'</span><span style="font-size:12px;color:#64748b;">'+esc(x.date)+'</span></div><div style="font-size:17px;font-weight:900;color:#1e293b;margin-top:6px;">'+esc((x.record.urunler&&x.record.urunler.length)?((x.record.urunler[0].name||x.record.urunler[0].urun||'Ürün')+(x.record.urunler.length>1?' + '+(x.record.urunler.length-1)+' ürün':'')):'İşlem kaydı')+'</div>'+(total?'<div style="font-size:17px;font-weight:900;color:#16a34a;margin-top:5px;">'+(typeof fmt==='function'?fmt(total):total.toFixed(2))+' €</div>':'')+'</div>';});if(filtered.length>PAGE)html+='<div style="display:flex;gap:8px;margin-top:12px;"><button onclick="window.WEICONSalesV2.historyPage(-1)" style="flex:1;padding:12px;border:1px solid #dbe4ef;border-radius:10px;background:#fff;">‹ Önceki</button><button onclick="window.WEICONSalesV2.historyPage(1)" style="flex:1;padding:12px;border:1px solid #dbe4ef;border-radius:10px;background:#fff;">Sonraki ›</button></div>';return html;}
  function contacts(){var m=requireCustomer();if(!m)return;state.contactType='all';showPanel('İŞLEMLER · MÜŞTERİ İLE TEMAS',contactsHtml());}
  function contactsData(){var m=currentCustomer();if(!m)return[];var arr=(m.ziyaretGecmisi||[]).slice();if(global.WEICONCustomerActivityAdapter){var normalized=global.WEICONCustomerActivityAdapter.fromCustomer(m);if(normalized.length&&!arr.length)arr=normalized.map(function(x){return{ts:Date.parse(x.date)||0,tur:x.type,not:x.note,kisi:null,fotolar:[]};});}return arr.sort(function(a,b){return(b.ts||0)-(a.ts||0);});}
  function normContact(t){var x=String(t||'').toLocaleLowerCase('tr-TR');if(x==='mesaj'||x==='whatsapp')return'whatsapp';if(x==='mail'||x==='email')return'mail';if(x==='telefon'||x==='phone'||x==='arama')return'telefon';if(x==='ziyaret'||x==='visit')return'ziyaret';return x||'ziyaret';}
  function contactsHtml(){var data=contactsData();var f=state.contactType==='all'?data:data.filter(function(x){return normContact(x.tur)===state.contactType;});var filters=['all','ziyaret','telefon','mail','whatsapp'];var labels={all:'Tümü',ziyaret:'Ziyaret',telefon:'Telefon',mail:'Mail',whatsapp:'WhatsApp'};var html='<div style="display:flex;gap:7px;overflow:auto;padding-bottom:8px;">';filters.forEach(function(k){html+='<button onclick="window.WEICONSalesV2.contactFilter(\''+k+'\')" style="white-space:nowrap;border:1px solid '+(state.contactType===k?'#0f766e':'#d5deea')+';background:'+(state.contactType===k?'#ecfdf5':'#fff')+';color:'+(state.contactType===k?'#0f766e':'#64748b')+';border-radius:20px;padding:8px 12px;font-weight:900;">'+labels[k]+'</button>';});html+='</div><button onclick="window.WEICONSalesV2.newContact()" style="width:100%;margin:4px 0 10px;border:0;border-radius:12px;background:#0f766e;color:#fff;padding:14px;font-weight:900;font-size:17px;">＋ Yeni Temas Notu</button>';if(!f.length)html+='<div style="padding:35px 10px;text-align:center;color:#94a3b8;font-weight:800;">Bu filtrede temas kaydı yok.</div>';f.forEach(function(x){var type=normContact(x.tur),icon={ziyaret:'📍',telefon:'☎️',mail:'✉️',whatsapp:'🟢'}[type]||'•';var dt=x.ts?new Date(x.ts).toLocaleString('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):(x.date||'-');html+='<div style="border-left:4px solid #0f766e;border-radius:12px;background:#fff;border-top:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;padding:13px;margin-top:9px;"><div style="display:flex;justify-content:space-between;gap:8px;"><b style="color:#0f766e;">'+icon+' '+labels[type]+'</b><span style="font-size:12px;color:#64748b;">'+esc(dt)+'</span></div>'+(x.kisi&&x.kisi.isim?'<div style="font-size:13px;color:#334155;margin-top:5px;">👤 '+esc(x.kisi.isim)+'</div>':'')+(x.not?'<div style="font-size:15px;color:#334155;line-height:1.45;margin-top:7px;">'+esc(x.not)+'</div>':'<div style="font-size:13px;color:#94a3b8;margin-top:7px;">Not girilmemiş.</div>')+'</div>';});return html;}
  function newContact(){closePanel();if(typeof musteriKartZiyaretAc==='function')musteriKartZiyaretAc();else if(typeof showToast==='function')showToast('Temas kaydı ekranı bulunamadı.');}
  function tasks(){var m=requireCustomer();if(!m)return;closeSales();if(typeof gorevListesiAc==='function')gorevListesiAc();else if(typeof showToast==='function')showToast('Görevler ekranı hazır değil.');}
  function closePanel(){var p=document.getElementById('salesV2Panel');if(p)p.remove();var modal=document.getElementById('satisMenusuModal');if(modal)modal.style.display='flex';}
  function showPanel(title,content){var old=document.getElementById('salesV2Panel');if(old)old.remove();var d=document.createElement('div');d.id='salesV2Panel';d.style.cssText='position:fixed;top:var(--ust-panel-h,150px);left:0;right:0;bottom:0;background:rgba(15,23,42,.62);z-index:10050;display:flex;align-items:flex-start;justify-content:center;padding-top:12px;box-sizing:border-box;';d.innerHTML='<div style="background:#fff;border-radius:20px;width:96%;max-width:760px;max-height:94vh;overflow:hidden;box-shadow:0 18px 60px rgba(0,0,0,.3);"><div style="background:#0b3b78;color:#fff;padding:17px 16px;display:flex;align-items:center;gap:10px;"><button onclick="window.WEICONSalesV2.closePanel()" style="border:0;background:rgba(255,255,255,.14);color:#fff;border-radius:10px;padding:7px 10px;font-size:21px;">‹</button><div style="font-size:20px;font-weight:900;flex:1;">'+title+'</div></div><div id="salesV2PanelContent" style="padding:14px;max-height:calc(94vh - 70px);overflow:auto;">'+content+'</div></div>';document.body.appendChild(d);}
  global.WEICONSalesV2={open:function(){state.tab='customer';render();},close:closeSales,tab:function(t){state.tab=t;renderTab();},customerCard:openCurrentCustomerCard,authorities:openAuthorities,startSale:startSale,history:history,historyFilter:function(t){state.historyType=t;state.historyPage=0;var el=document.getElementById('salesV2PanelContent');if(el)el.innerHTML=historyHtml();},historyPage:function(d){state.historyPage=Math.max(0,state.historyPage+d);var el=document.getElementById('salesV2PanelContent');if(el)el.innerHTML=historyHtml();},contacts:contacts,contactFilter:function(t){state.contactType=t;var el=document.getElementById('salesV2PanelContent');if(el)el.innerHTML=contactsHtml();},newContact:newContact,tasks:tasks,closePanel:closePanel};
  global.satisMenusuAc=function(){global.WEICONSalesV2.open();};
})(window);
